Jaehyuk-Lee/carematching-backend

.env.template, build.gradle, src/main/resources/application.yaml
Oracle RDS 비용 문제를 고려해서 mariaDB로 전환하기로 하였음.
=> change to mariaDB

src/main/java/com/sesac/carematching/chat/message/Message.java, src/main/java/com/sesac/carematching/chat/room/Room.java, src/main/java/com/sesac/carematching/community/comment/Comment.java, src/main/java/com/sesac/carematching/community/like/Like.java, src/main/java/com/sesac/carematching/community/post/Post.java, src/main/java/com/sesac/carematching/community/viewcount/Viewcount.java, src/main/java/com/sesac/carematching/notification/Notification.java, src/main/java/com/sesac/carematching/user/User.java
`@CreatedDate`와 `@LastModifiedDate`를 사용하기 위해서 필요한 내용 추가
=> Enable JPA auditing for entity classes

src/main/java/com/sesac/carematching/caregiver/Caregiver.java
@jeeyun2 오늘 낮에 코드리뷰할 때 이 부분 네이밍 컨벤션 놓쳤네요.
내일 확인하시고 merge 해주세요.
=> match naming convention

src/main/java/com/sesac/carematching/user/UserController.java, src/main/java/util/TokenAuth.java
사용자 토큰 인증이 필요한 경우, `TokenAuth` 클래스의 `extractUsernameFromToken` 메서드를 사용해주세요.
=> 토큰 인증 로직을 별도의 유틸리티 클래스로 추출

src/main/java/com/sesac/carematching/config/SecurityConfig.java
#3 commit에서 빠뜨린 부분
* JWT Token 사용으로 authorizeHttpRequests 제거
=> 세션 인증과 연관된 authorization 요청 제거

src/main/java/com/sesac/carematching/user/UserController.java
`GET`과 `POST` 요청만 사용하기로 합의하여 `DELETE` 요청을 `POST`요청으로 변경합니다.
=> delete user: DeleteMapping to PostMapping

src/main/java/com/sesac/carematching/transaction/Status.java, src/main/java/com/sesac/carematching/transaction/Transaction.java, src/main/java/com/sesac/carematching/transaction/TransactionController.java, src/main/java/com/sesac/carematching/transaction/TransactionRepository.java, src/main/java/com/sesac/carematching/transaction/TransactionService.java, src/main/java/com/sesac/carematching/transaction/dto/TransactionAddDTO.java, src/main/java/com/sesac/carematching/transaction/dto/TransactionGetDTO.java, src/main/java/com/sesac/carematching/transaction/dto/TransactionMakeDTO.java, src/main/java/com/sesac/carematching/user/UserService.java
결제 관련 처리를 담당합니다.
`/api/transactions/add`에 `POST`방식으로 아래와 같은 형태의 정보를 같이 넘겨주면
```JSON
{
"cno": "1",
"uno": "3"
}
```
백엔드에서 결제 데이터 생성 후, `f41037eb-a90c-4bbe-979d-00f9351bd26c` 왼쪽과 같은 형태의 결제 UUID를 넘겨줍니다.
`/api/transactions/e613a391-299c-4764-9bc5-ef2b46854969`와 같이 UUID를 넘겨주면 해당 결제 ID에 해당하는 정보를 넘겨줍니다. (`GET`방식) 아래는 응답 예시.
```JSON
{
"caregiverName": "이준우",
"userName": "user01",
"price": 3000000
}
```
=> Transaction 추가

src/main/java/com/sesac/carematching/caregiver/Caregiver.java, src/main/java/com/sesac/carematching/caregiver/CaregiverController.java, src/main/java/com/sesac/carematching/caregiver/CaregiverService.java, src/main/java/com/sesac/carematching/caregiver/dto/BuildCaregiverDto.java, src/main/java/com/sesac/carematching/caregiver/dto/CaregiverDetailDto.java, src/main/java/com/sesac/carematching/experience/Experience.java, src/main/java/com/sesac/carematching/experience/ExperienceRepository.java, src/main/java/com/sesac/carematching/experience/ExperienceRequest.java, src/main/java/com/sesac/carematching/experience/ExperienceResponse.java, src/main/java/com/sesac/carematching/experience/ExperienceService.java
1. 새로 로직을 짜 experience에 대한 service, repository, entity, dto 등을 추가
2. CaregiverController 내의 getMapping, update와 create 등이 experienceList를 같이 넣어 동작하도록 수정
3. caregiver의 dto 안에 또 experience Dto를 넣어 experience의 내용을 잘 가져갈 수 있도록 함
=> ExperienceList

src/main/java/com/sesac/carematching/community/post/PostRepository.java, src/main/java/com/sesac/carematching/util/S3UploadService.java
* 백엔드에서도 업로드한 파일이 이미지가 맞는지 검증합니다.
* 인기글이 좋아요 많은순에서 최신순으로 변경되었습니다.
=> 이미지 파일 검증, 인기글 최신순으로 변경

src/main/java/com/sesac/carematching/community/post/PostService.java
* 일반 사용자가 url을 통해 요양사 게시글 상세에 접근할 수 있는 문제를 해결했습니다.
=> 요양사 전용 게시글 상세 접근 강화

src/main/java/com/sesac/carematching/caregiver/CaregiverController.java, src/main/java/com/sesac/carematching/caregiver/dto/CaregiverListDto.java
null point 에러로 등록이 되지 않는 문제 수정
=> register 수정

src/main/java/com/sesac/carematching/chat/config/RedisConfig.java, src/main/java/com/sesac/carematching/chat/controller/NotificationController.java, src/main/java/com/sesac/carematching/chat/listener/RedisSubscriber.java, src/main/java/com/sesac/carematching/chat/service/MessageServiceImpl.java, src/main/java/com/sesac/carematching/chat/service/NotificationService.java, src/main/java/com/sesac/carematching/chat/service/RoomServiceImpl.java, src/main/resources/application.yaml
=> redis 환경변수 & 주석처리

src/main/java/com/sesac/carematching/transaction/Transaction.java
=> Fix Transaction Entity

src/main/resources/data.sql
=> data.sql 수정

src/main/java/com/sesac/carematching/CarematchingApplication.java
배포된 환경에서는 UTC로 기본 설정되어 UTC+9로 변경해줌
=> update Timezone to UTC+9

src/main/java/com/sesac/carematching/transaction/TransactionService.java
=> fix transaction error

src/main/java/com/sesac/carematching/user/UserController.java, src/main/java/com/sesac/carematching/user/UserService.java, src/main/java/com/sesac/carematching/user/dto/StatusDTO.java
* POST/GET 만 사용하고 있다는 점은 아직 REST API를 완벽히 구현하지는 않음.
* 상태 변경 메서드를 하나로 통합 (기존에는 true로 바꾸는 메서드, false로 바꾸는 메서드를 따로 만들었었음)
=> REST API 원칙에 가까워지도록 개선

src/main/java/com/sesac/carematching/config/GlobalExceptionHandler.java, src/main/java/com/sesac/carematching/transaction/TransactionController.java, src/main/java/com/sesac/carematching/transaction/TransactionService.java, src/main/java/com/sesac/carematching/transaction/dto/TossPaymentsErrorResponseDTO.java, src/main/java/com/sesac/carematching/transaction/dto/TransactionVerifyDTO.java, src/main/java/com/sesac/carematching/transaction/exception/TossPaymentsException.java, src/main/resources/application.yaml
1. **TossPayments 결제 검증 로직 추가**
- Service 계층에 `verifyTossPayment` 메서드 구현
- TossPayments 결제 검증 API(`/v1/payments/confirm`)에 POST 요청하여 결제 성공 여부 확인
- 시크릿키는 환경 변수(`toss.secret`)로 관리하여 보안 강화
2. **결제 검증 API 및 DTO 적용**
- `/api/transactions/verify/{paymentKey}` 엔드포인트 추가
- 결제 검증 요청 시 `TransactionVerifyDTO`를 통해 orderId, price, paymentKey를 전달받아 검증
- 결제 검증 성공 시 트랜잭션 상태를 SUCCESS로 변경 및 응답, 실패 시 예외 처리
3. **설정 파일(application.yaml) 변경**
- TossPayments 시크릿키 환경 변수(`toss.secret`) 추가
- 프론트엔드에서 결제 성공 후 TossPayments에서 받은 paymentKey, orderId, 결제 금액을 백엔드로 전달하면, 백엔드에서 실제 결제 성공 여부를 TossPayments API를 통해 검증합니다.
- 검증이 성공하면 트랜잭션 상태를 SUCCESS로 변경하고, 검증 결과를 응답합니다.
- 결제 검증 실패 시 예외를 반환하여 프론트엔드에서 실패 처리를 할 수 있습니다.
- 시크릿키는 환경 변수로 관리되어 운영 환경에서도 안전하게 사용할 수 있습니다.
- **엔드포인트:**  `POST /api/transactions/verify/{paymentKey}`
- **요청 …
=> feat: TossPayments 결제 검증 기능 및 API 적용

src/main/java/com/sesac/carematching/transaction/TransactionService.java
- TossPayments 결제 검증(verifyTossPayment) RestTemplate에 타임아웃 설정을 추가했습니다.
- 1회차 5초, 2회차 17.5초, 3회차 30초로 시도할 때마다 timeout이 점진적으로 증가하도록 구현했습니다.
- Toss 공식 권장(30초)과 UX(5초) 모두를 고려하여, 대부분의 거래는 빠르게 처리하고 장애 상황에서는 충분히 대기할 수 있도록 했습니다.
- 토스페이먼츠 개발자 센터 문서: https://techchat.tosspayments.com/m/1261254382864039996
- RestTemplate 기본값(무제한)
- 각 시도별 timeout을 동적으로 계산하여 적용 (최소 5초, 최대 30초)
=> feat: TossPayments 결제 검증 시 타임아웃 설정 및 점진적 증가 적용

src/main/java/com/sesac/carematching/chat/config/WebSocketConfig.java, src/main/java/com/sesac/carematching/chat/controller/MessageController.java, src/main/java/com/sesac/carematching/chat/pubsub/ChatMessageSubscriber.java, src/main/java/com/sesac/carematching/chat/pubsub/NotificationSubscriber.java, src/main/java/com/sesac/carematching/chat/pubsub/RedisPublisherService.java, src/main/java/com/sesac/carematching/chat/service/ChatMessageService.java, src/main/java/com/sesac/carematching/chat/service/MessageServiceImpl.java, src/main/java/com/sesac/carematching/chat/service/NotificationService.java
이번 PR은 다음 두 가지 변경 사항으로 요약할 수 있습니다.
1. 채팅 메시지를 Redis Pub/Sub 기반으로 다중 인스턴스간 동기화 구현
2. Redis라는 공통된 기능을 모아 파일/디렉토리명 통합
- `MessageServiceImpl`에서 채팅 메시지 저장 후 Redis를 통해 메시지 발행
- `ChatMessageSubscriber`를 통해 Redis에서 수신한 메시지를 WebSocket으로 전달
- `RedisPublisherService` 추가
- `WebSocketConfig` 주석 정리
- `MessageController`에서 메시지 발행 방식 개선 (기존 인스턴스 + Redis Pub/Sub 동기화)
- `RedisSubscriber` → `NotificaionSubscriber`로 이름 변경 (채팅 메시지 Subscriber와 혼동 방지)
- `NotificationService`에서 `RedisPublisherService`를 사용하여 알림 발행
=> feat: Redis Pub/Sub 기반 채팅 동기화 추가 및 Redis 기능 통합 리팩토링
